### PR TITLE
FizzBuzz

### PR DESCRIPTION
**Pull request by Shashankjain12**
Please make sure you have done the following:

- [x] Created a folder with the name of language you code inside `/Day<n>/` directory (Where n is for nth day)
- [x] Added your Codes
- [x] Tested your codes
- [x] Added credits (author and date) at the top of the code
- [x] Updated README.md
- [x] Added yourself as a contributor using `all-conributors-cli`

### CODE REVIEW

**Comment by Shashankjain12** [comment]
Day1 completed

**Comment by Shashankjain12** [comment]
Day 1 Updated

**Comment by MadhavBahlMD** [comment]
Why did you remove the names of other contributors though? 🤔

**Comment by Shashankjain12** [comment]
I thought that it will be a way to do that..😅😅

**Pull request closed without merging**
